# Generated by Django 5.1.4 on 2024-12-23 14:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterqualityanalysis',
            old_name='analysis_date',
            new_name='analysis_end_date',
        ),
        migrations.RemoveField(
            model_name='waterqualityanalysis',
            name='stats_path',
        ),
        migrations.AddField(
            model_name='reservoir',
            name='users',
            field=models.ManyToManyField(related_name='reservoirs', to='api.user'),
        ),
        migrations.AddField(
            model_name='waterqualityanalysis',
            name='analysis_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waterqualityanalysis',
            name='reservoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='api.reservoir'),
        ),
    ]
