# Generated by Django 5.1.4 on 2025-01-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisrequest',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='analysisrequest',
            name='analysis_request_status',
        ),
        migrations.RemoveField(
            model_name='analysisrequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='machinelearningmodel',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='machinelearningmodel',
            name='reservoir',
        ),
        migrations.DeleteModel(
            name='AnalysisMachineLearningModel',
        ),
        migrations.DeleteModel(
            name='AnalysisRequestStatus',
        ),
        migrations.DeleteModel(
            name='AnalysisRequest',
        ),
        migrations.DeleteModel(
            name='MachineLearningModel',
        ),
    ]
