# Generated by Django 5.1.4 on 2025-01-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reservoirparametermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservoirparametermodel',
            old_name='model_path',
            new_name='model_filename',
        ),
        migrations.RenameField(
            model_name='reservoirparametermodel',
            old_name='scaler_path',
            new_name='scaler_filename',
        ),
        migrations.RemoveField(
            model_name='reservoirparametermodel',
            name='model_file',
        ),
        migrations.RemoveField(
            model_name='reservoirparametermodel',
            name='scaler_file',
        ),
    ]
