# Generated by Django 5.1.4 on 2025-01-26 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_analysisrequest_analysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'analysis_request_status',
            },
        ),
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('properties', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.analysis')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('analysis_request_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.analysisrequeststatus')),
            ],
            options={
                'db_table': 'analysis_request',
            },
        ),
        migrations.CreateModel(
            name='MachineLearningModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file', models.BinaryField()),
                ('scaler_file', models.BinaryField()),
                ('model_file_hash', models.CharField(max_length=64)),
                ('scaler_file_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parameter')),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reservoir')),
            ],
            options={
                'db_table': 'machine_learning_model',
            },
        ),
        migrations.CreateModel(
            name='AnalysisMachineLearningModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raster_path', models.CharField(max_length=255)),
                ('intensity_map', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.analysis')),
                ('machine_learning_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.machinelearningmodel')),
            ],
            options={
                'db_table': 'analysis_machine_learning_model',
            },
        ),
        migrations.AddConstraint(
            model_name='machinelearningmodel',
            constraint=models.UniqueConstraint(fields=('model_file_hash',), name='unique_file_hashes'),
        ),
    ]
