# Generated by Django 5.1.4 on 2025-01-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_analysisrequeststatus_analysisrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysismachinelearningmodel',
            name='raster_path',
            field=models.TextField(),
        ),
    ]
