# Generated by Django 5.1.4 on 2025-01-08 04:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_model_path_reservoirparametermodel_model_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservoirparametermodel',
            name='model_path',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservoirparametermodel',
            name='scaler_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
    ]
