# Generated by Django 5.1.4 on 2025-01-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reservoirparametermodel_model_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterqualityanalysisparameters',
            name='intensity_map_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
