# Generated by Django 5.1.4 on 2024-12-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$mzLS93fgxjj5NXX2ecwqi6$BvB/6pPyjA7+FqEekZgyZs+Tolc7qRdVimbi+Fde2Fk=', max_length=128),
        ),
    ]
