# Generated by Django 5.1.4 on 2024-12-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Pv9GfOVLGgJA7S8QZKKf9J$sFv+88V3JtzcN1aI+nYt13M0zuQ3kOX2G5GHzWQZj00=', max_length=128),
        ),
    ]
