# Generated by Django 5.1.4 on 2025-01-30 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_analysismachinelearningmodel_static_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_code', models.UUIDField(unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reservoir')),
            ],
            options={
                'db_table': 'analysis_group',
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='analysis_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.analysisgroup'),
            preserve_default=False,
        ),
    ]
