# Generated by Django 5.1.4 on 2025-01-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_waterqualityanalysisparameters_intensity_map_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterqualityanalysisparameters',
            name='intensity_map_path',
        ),
        migrations.AddField(
            model_name='waterqualityanalysisparameters',
            name='intensity_map',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
