# Generated by Django 5.1.4 on 2025-01-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_waterqualityanalysisparameters_intensity_map_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterqualityanalysisparameters',
            name='analysis_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
