# Generated by Django 5.1.4 on 2025-01-17 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_waterqualityanalysisparameters_analysis_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterqualityanalysis',
            name='analysis_end_date',
        ),
        migrations.RemoveField(
            model_name='waterqualityanalysis',
            name='analysis_start_date',
        ),
    ]
