# Generated by Django 5.1.4 on 2025-01-17 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_reservoirparametermodel_reservoirparametermodelscaler_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterqualityanalysisparameter',
            name='analysis_date',
        ),
        migrations.AddField(
            model_name='waterqualityanalysis',
            name='analysis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservoir',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
