# Generated by Django 5.1.4 on 2025-01-23 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_waterqualityanalysis_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterqualityanalysisparameter',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='waterqualityanalysisparameter',
            name='min_value',
        ),
        migrations.CreateModel(
            name='MachineLearningModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file_hash', models.CharField(max_length=64)),
                ('scaler_file_hash', models.CharField(max_length=64)),
                ('model_file', models.BinaryField()),
                ('scaler_file', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_models', to='api.parameter')),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_models', to='api.reservoir')),
            ],
            options={
                'db_table': 'machine_learning_model',
                'unique_together': {('reservoir', 'parameter', 'model_file_hash', 'scaler_file_hash')},
            },
        ),
        migrations.DeleteModel(
            name='ReservoirParameterModelScaler',
        ),
    ]
