# Generated by Django 5.1.4 on 2025-01-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_waterqualityanalysisparameter_max_value_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='machinelearningmodel',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='machinelearningmodel',
            constraint=models.UniqueConstraint(fields=('model_file_hash', 'scaler_file_hash'), name='unique_file_hashes'),
        ),
        migrations.AlterModelTable(
            name='machinelearningmodel',
            table=None,
        ),
    ]
